<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CQ\Commands\AssignCourier\" />
    <Folder Include="CQ\Commands\OrderLine\AddOrderLine\" />
    <Folder Include="CQ\Commands\OrderLine\RemoveOrderLine\" />
    <Folder Include="CQ\Commands\ChangeOrderStatus\" />
    <Folder Include="CQ\Commands\OrderLine\ChangeOrderLineStatus\" />
    <Folder Include="CQ\Commands\OrderLine\UpdateOrderLineQuantity\" />
    <Folder Include="CQ\Commands\OrderLine\" />
    <Folder Include="Features\Pipelines\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" Version="2.0.1" />
    <PackageReference Include="FluentValidation" Version="11.9.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.1" />
    <PackageReference Include="MediatR" Version="12.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\LuckyFoodSystem.Utils\LuckyFoodSystem.Shared\LuckyFoodSystem.Shared.csproj" />
  </ItemGroup>

</Project>
