<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>df874f64-df2d-4b45-8d9b-835c8acd7a5c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LuckyFoodSystem.Orders.Bll\LuckyFoodSystem.Orders.Bll.csproj" />
    <ProjectReference Include="..\LuckyFoodSystem.Orders.Infrastructure\LuckyFoodSystem.Orders.Infrastructure.csproj" />
  </ItemGroup>

</Project>
